export const yearFilter = [
  { value: "", label: "Все годы" },
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2010-2019", label: "2010-2019" },
  { value: "2000-2009", label: "2000-2009" },
  { value: "1990-1999", label: "1990-1999" },
  { value: "1980-1989", label: "1980-1989" },
  { value: "1970-1979", label: "1970-1979" },
  { value: "1960-1969", label: "1960-1969" },
  { value: "1950-1959", label: "1950-1959" },
  { value: "1940-1949", label: "1940-1949" },
  { value: "1930-1939", label: "1930-1939" },
];

// Можно было запилить запросом по всем странам
export const countryFilter = [
  { value: "", label: "Все страны" },
  { value: "Россия", label: "Россия" },
  { value: "США", label: "США" },
  { value: "СССР", label: "СССР" },
  { value: "Франция", label: "Франция" },
  { value: "Италия", label: "Италия" },
  { value: "Великобритания", label: "Великобритания" },
  { value: "Китай", label: "Китай" },
  { value: "Германия", label: "Германия" },
  { value: "Канада", label: "Канада" },
  { value: "Япония", label: "Япония" },
  { value: "Венгрия", label: "Венгрия" },
  { value: "Турция", label: "Турция" },
  { value: "Мексика", label: "Мексика" },
  { value: "Австралия", label: "Австралия" },
  { value: "Новая Зеландия", label: "Новая Зеландия" },
  { value: "Корея Южная", label: "Корея Южная" },
  { value: "ЮАР", label: "ЮАР" },
  { value: "Швейцария", label: "Швейцария" },
  { value: "Таиланд", label: "Таиланд" },
  { value: "Нидерланды", label: "Нидерланды" },
  { value: "Украина", label: "Украина" },
  { value: "Беларусь", label: "Беларусь" },
  { value: "Польша", label: "Польша" },
  { value: "Швеция", label: "Швеция" },
  { value: "Чехия", label: "Чехия" },
];

export const ageRatingFilter = [
  { value: "", label: "Для всей семьи" },
  { value: "6-18", label: "6+" },
  { value: "12-18", label: "12+" },
  { value: "18", label: "18+" },
];
